build:
  image: python:3.5
  environment:
    - PYTHONPATH=$BUILD_DIR
  commands:
    - env
    - pip3.5 install -r requirements.txt
    - pelican -s publishconf.py

deploy:
  rsync:
    user: twiw
    host: kaneda.kaed.uk
    source: output/*
    target: ~/htdocs
    delete: true
    recursive: true

    when:
      branch: master
